# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.24'

# Starter pipeline
- task: TerraformTaskV1@0

  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'bterkaly-juchizer(191f97dd-acdd-423c-aad7-b966e3511182)'
    backendAzureRmResourceGroupName: 'terraformsa'
    backendAzureRmStorageAccountName: 'chizerterraform'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'prod.terraform.tfstate'


- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'bterkaly-juchizer(191f97dd-acdd-423c-aad7-b966e3511182)'


- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'bterkaly-juchizer(191f97dd-acdd-423c-aad7-b966e3511182)'